### ISSUE TITLE
:sparkles: Missing middleware

### ISSUE THREAD

**Issue by Sigmanificient** [Pincer-org/Pincer#229]
```py
user_settings_update
channel_unread_update
sessions_replace
message_ack
relationship_add                             # when sending friend req or blocking someone yo wtf? xD
guild_application_command_counts_update      # when adding a bot with built-in button
channel_pins_ack                             # pin a msg
relationship_remove
payment_update                               # buyin nitro
call_create                                  # create call
call_update                                  # joining call, discord fix your middlewares ._.
call_delete
user_guild_settings_update                   # mute someone, yo wtf? xD
user_note_update
user_settings_proto_update                   # joing edu program
guild_scheduled_event_user_create
user_connections_update                      # add yt acc
```

**Comment by Sigmanificient** [comment]
seems like all of thoses middlewares are not documented :)

**Comment by Endercheif** [comment]
They aren’t suppose to be implemented. There are two types of event: RPC and Gateway. Gateway is the one we recently completed. It is what discord means by events and what the discord bot api supports. RPC on the other hand is NOT meant for bots. It instead is implemented by standalone apps (think video games). Recently however, it has been in beta and is becoming obsolete in favour of [idr the name of it]. The point is we should **NOT** implement it because we would need to create a brand new client object and the support is limited.
