### ISSUE TITLE
Python 3.7 Does not support 'typing.Protocol'

### ISSUE THREAD

**Issue by Endercheif** [Pincer-org/Pincer#23]
**Describe the bug**
Python 3.7 does not support `typing.Protocol`.

**To Reproduce**

1.  Run code in python 3.7
2.  Get an error
`ImportError: cannot import name 'Protocol' from 'typing' (/usr/lib/python3.7/typing.py)`

**Comment by Endercheif** [comment]
Either we remove `typing.Protocol` or update to Python 3.8

**Comment by Sigmanificient** [comment]
I've seen some prod server still using `3.7.2` so would like to try keeping the `3.7` version, even tho they are getting rare.
Most of then are in `3.8.6` or `3.9`.

It was not a real problem for me to drop the `3.6` since the end of support is coming very soon anyway `2021-12-23`
But the 3.7 is still supported until `2023-06-27` (see on [Active Python Releases](https://www.python.org/downloads))

**Comment by Sigmanificient** [comment]
It has been decided for pincer to stop the python 3.7 support, and focusing on python 3.8 as the minimum required version to use the library
